import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useRef, useState, useEffect } from 'react'
import { providers } from 'ethers'
import Web3Modal from "web3modal"


export default function Home() {

  const [walletConnected, setWalletConnected] = useState(false)
  const [address, setAddress] = useState("")
  const [ENS, setENS] = useState("")
  const web3ModalRef = useRef()

  const getProviderOrSigner = async () => {
    const provider = await web3ModalRef.current.connect();
    const web3Provider = new providers.Web3Provider(provider);

    const { chainId } = await web3Provider.getNetwork();
    if (chainId !== 5) {
      window.alert("Change the network to Goerli");
      throw new Error("Change network to Goerli");
    }

    const signer = web3Provider.getSigner();
    const address = await signer.getAddress()
    console.log(address)
    await setENSOrAddress(address, web3Provider)
    return web3Provider;
  }

  const connectWallet = async () => {
    try {
      console.log("i")
      await getProviderOrSigner();
      setWalletConnected(true);
    } catch (err) {
      console.error(err);
    }
  }

  const setENSOrAddress = async (address, web3Provider) => {
    var _ens = await web3Provider.lookupAddress(address);
    if (_ens) {
      setENS(_ens);
    } else {
      setAddress(address);
    }
  };

  useEffect(() => {
    if(!walletConnected) {
      web3ModalRef.current = new Web3Modal({
        network: "goerli",
        providerOptions: {},
        disableInjectedProvider: false,
      })
      connectWallet()
    }
  }, [walletConnected])

  const renderButton = () => {
      if (walletConnected) {
        return (<button onClick={connectWallet} className={styles.button}>
            Wallet connected
        </button>)
      } else {
        return (
          <button onClick={connectWallet} className={styles.button}>
            Connect your wallet
          </button>
        );
      }
  }

  return (
    <div>
      <Head>
        <title>ENS dApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <h1 className={styles.title}>Welcome to LearnWEB3 frens - {ENS != "" ? ENS : address.substring(0,6)+"..."+address.substring(address.length-6)}</h1>
        <div className={styles.description}>Frens are a NFT collection for LearnWeb3 students</div>
        {renderButton()}
        <img className={styles.image} src="./learn.png"></img>
      </div>
      <footer className={styles.footer}> Made with &#10084; by Purif </footer>
    </div>
  )
}
